// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBrVFjjXeptMuPSipOmhFx-TFGvLJByJZc',
    appId: '1:20397453026:web:2bd59d7e8d04a752d478bb',
    messagingSenderId: '20397453026',
    projectId: 'flutter-base-flaver',
    authDomain: 'flutter-base-flaver.firebaseapp.com',
    storageBucket: 'flutter-base-flaver.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCG9pC6OnXSG1H6sNFNpiAHAnsHjV7R-vc',
    appId: '1:20397453026:android:e1f971aed519ac1fd478bb',
    messagingSenderId: '20397453026',
    projectId: 'flutter-base-flaver',
    storageBucket: 'flutter-base-flaver.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBFqoDmfJOmsR_GQfyuA5bZIYzIu16rG4k',
    appId: '1:20397453026:ios:690fcb27b601a621d478bb',
    messagingSenderId: '20397453026',
    projectId: 'flutter-base-flaver',
    storageBucket: 'flutter-base-flaver.appspot.com',
    iosClientId: '20397453026-5cm6u16npcmvcdnnjl60fdlt2a7tiktm.apps.googleusercontent.com',
    iosBundleId: 'com.example.baseFlaver.prod',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBFqoDmfJOmsR_GQfyuA5bZIYzIu16rG4k',
    appId: '1:20397453026:ios:ca0297f722b904aad478bb',
    messagingSenderId: '20397453026',
    projectId: 'flutter-base-flaver',
    storageBucket: 'flutter-base-flaver.appspot.com',
    iosClientId: '20397453026-uqbo5gspo220nujmmloogks7113h3seg.apps.googleusercontent.com',
    iosBundleId: 'com.example.baseFlaver',
  );
}
